import random
import psutil
from fastapi import APIRouter
from app.services.simulation import sim_state

router = APIRouter(prefix="/api", tags=["monitor"])

@router.get("/monitor")
def get_monitor_stats():
    # 1. Master load is the actual host CPU load
    master_cpu = psutil.cpu_percent()
    
    # 2. Simulate Node loads based on active run configuration
    nodes_count = max(4, sim_state.nodes)
    node_loads = [2.0] * nodes_count # default idle loads
    
    if sim_state.is_running:
        # Distribute active processes across the selected nodes
        procs = sim_state.processes
        nodes = sim_state.nodes
        
        # Base active CPU load
        active_load = 75.0 + random.uniform(-10.0, 15.0)
        active_load = min(100.0, max(0.0, active_load))
        
        for idx in range(nodes_count):
            # If the node is selected and has processes mapped
            if idx < nodes:
                # Calculate simple process load factor
                node_procs = (procs // nodes) + (1 if idx < (procs % nodes) else 0)
                if node_procs > 0:
                    max_procs_per_node = max(1, 16 // nodes)
                    node_loads[idx] = active_load * (0.6 + 0.4 * (node_procs / max_procs_per_node))
                    node_loads[idx] = min(100.0, node_loads[idx])
                else:
                    node_loads[idx] = 5.0 + random.uniform(0.0, 5.0)
            else:
                node_loads[idx] = 1.0 + random.uniform(0.0, 2.0)
    else:
        # Idle fluctuations
        for idx in range(nodes_count):
            node_loads[idx] = 2.0 + random.uniform(-1.0, 3.0)
            
    # Mock network traffic generated by MPI communications
    network_traffic = 0.0
    if sim_state.is_running:
        network_traffic = sim_state.processes * sim_state.nodes * (12.4 + random.uniform(-1.5, 3.5)) # MB/s
        
    response = {
        "master": round(master_cpu, 1),
        "networkTraffic": round(network_traffic, 1)
    }
    for idx in range(nodes_count):
        response[f"node{idx+1}"] = round(node_loads[idx], 1)
        
    return response

